export const actionTypes = {
    SET_LOCALE: 'SET_LOCALE',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
    EMPTY_WISHLIST: 'EMPTY_WISHLIST',
    SET_USER: 'SET_USER',
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    INCREMENT: 'INCREMENT'
  };